apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deploy
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:6.8.22
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-svc.default.svc.cluster.local:9200
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30040
  selector:
    app: kibana
